# Generated by Django 5.1.7 on 2026-04-18 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupons_cou_code_3bf721_idx',
            old_name='coupons_cou_code_5106e8_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupons_cou_is_acti_a50634_idx',
            old_name='coupons_cou_is_acti_e3c6b2_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupons_cou_valid_f_ac5256_idx',
            old_name='coupons_cou_valid_f_d9861d_idx',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
