# Generated by Django 5.1.7 on 2026-04-16 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_singleton_defaults(apps, schema_editor):
    StoreConfiguration = apps.get_model("shop", "StoreConfiguration")
    LegalPageContent = apps.get_model("shop", "LegalPageContent")
    AboutPageContent = apps.get_model("shop", "AboutPageContent")

    if not StoreConfiguration.objects.exists():
        StoreConfiguration.objects.create(
            name="My Store",
            tagline="Your store tagline",
            description="Default store description.",
            currency="USD",
            timezone="UTC",
            language="en",
            tax=0,
        )

    if not LegalPageContent.objects.exists():
        LegalPageContent.objects.create(
            privacy_policy="Default privacy policy content.",
            terms_and_conditions="Default terms and conditions content.",
        )

    if not AboutPageContent.objects.exists():
        AboutPageContent.objects.create(
            story_title="Our Story",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPageContent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("privacy_policy", models.TextField(default="Default privacy policy content.")),
                ("terms_and_conditions", models.TextField(default="Default terms and conditions content.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Page Content",
                "verbose_name_plural": "Legal Page Content",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AboutPageContent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cover_image", models.URLField(blank=True, null=True)),
                ("left_text_content", models.TextField(blank=True, default="")),
                ("right_text_content", models.TextField(blank=True, default="")),
                ("store_image", models.URLField(blank=True, null=True)),
                ("story_title", models.CharField(blank=True, default="", max_length=255)),
                ("story_content", models.TextField(blank=True, default="")),
                ("served_customer_count", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                ("styles_count", models.PositiveIntegerField(default=0)),
                ("detail_section_title", models.CharField(blank=True, default="", max_length=255)),
                ("detail_1_image", models.URLField(blank=True, null=True)),
                ("detail_1_title", models.CharField(blank=True, default="", max_length=255)),
                ("detail_2_image", models.URLField(blank=True, null=True)),
                ("detail_2_title", models.CharField(blank=True, default="", max_length=255)),
                ("detail_3_image", models.URLField(blank=True, null=True)),
                ("detail_3_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page Content",
                "verbose_name_plural": "About Page Content",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["created_at"],
            },
        ),
        migrations.RunPython(create_singleton_defaults, migrations.RunPython.noop),
    ]
