# Generated by Django 5.1.7 on 2026-04-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nylo_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminpermission',
            new_name='nylo_auth_a_admin_p_d7b148_idx',
            old_name='nylo_auth_a_admin_p_6e42d0_idx',
        ),
    ]
