# Generated by Django 5.1.7 on 2026-04-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nylo_auth', '0003_admininvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admininvitation',
            new_name='nylo_auth_a_email_823f03_idx',
            old_name='nylo_auth_a_email_a982d1_idx',
        ),
    ]
