# Generated by Django 5.1.7 on 2026-04-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nylo_auth', '0005_redesign_admin_authorization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminpermission',
            new_name='nylo_auth_a_admin_p_80f8f8_idx',
            old_name='nylo_auth_a_admin_p_9a1435_idx',
        ),
    ]
