# Generated by Django 5.1.7 on 2026-04-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nylo_auth', '0006_rename_nylo_auth_a_admin_p_9a1435_idx_nylo_auth_a_admin_p_80f8f8_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininvitation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='admininvitation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admininvitation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admininvitation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='role',
        ),
    ]
