# Generated by Django 5.1.7 on 2026-04-11 06:36

import secrets
import string

from django.db import migrations, models


TRACKING_NUMBER_ALPHABET = string.ascii_uppercase + string.digits


def generate_tracking_number(length=8):
    return "".join(secrets.choice(TRACKING_NUMBER_ALPHABET) for _ in range(length))


def populate_tracking_numbers(apps, schema_editor):
    Order = apps.get_model("orders", "Order")

    for order in Order.objects.filter(tracking_number__isnull=True):
        tracking_number = generate_tracking_number()
        while Order.objects.filter(tracking_number=tracking_number).exists():
            tracking_number = generate_tracking_number()

        order.tracking_number = tracking_number
        order.save(update_fields=["tracking_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(populate_tracking_numbers, migrations.RunPython.noop),
    ]
