# Generated by Django 5.1.7 on 2026-04-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='promo_code',
            new_name='coupon_code',
        ),
    ]
